version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}