spring:
  application:
    name: DB_Project_2024
  datasource:
    url: jdbc:postgresql://localhost:5432/db_project
    username: postgres
    password: 123123123
    driver-class-name: org.postgresql.Driver
